/**
 * Component docs metadata — powers Accessibility / Performance / Related sections.
 * Curated, not generated. Fallbacks keep every page honest when unmapped.
 */

export type PerfLevel = "lightweight" | "moderate" | "heavy";

export const PERFORMANCE: Record<string, { level: PerfLevel; note: string }> = {
  "magnetic-button": { level: "lightweight", note: "Pointer handler only; transform + opacity. No canvas." },
  "liquid-button": { level: "lightweight", note: "CSS blob; pointer-tracked custom property." },
  "magnetic-card": { level: "lightweight", note: "Tilt via transform; spotlight radial gradient." },
  "slingshot-otp": { level: "moderate", note: "rAF game loop only in game mode; standard mode is static." },
  "particle-field": { level: "moderate", note: "Canvas with DPR cap and bounded count. Reduce count on weak hardware." },
  "aurora-background": { level: "lightweight", note: "Pure CSS drift; disabled under reduced motion." },
  "streaming-chat": { level: "lightweight", note: "Interval streamer; no network. Bring your own LLM backend." },
  "advanced-table": { level: "lightweight", note: "Client filter/sort/paginate; virtualize beyond ~500 rows." },
  "spreadsheet-grid": { level: "moderate", note: "One input per cell; cap grid size for large sheets." },
  kanban: { level: "moderate", note: "HTML5 drag + keyboard move; no physics engine." },
  "node-editor": { level: "moderate", note: "Static SVG; zoom via transform scale." },
  terminal: { level: "lightweight", note: "Scrollback list; autoscroll on append." },
};

export function perfFor(slug: string): { level: PerfLevel; note: string } {
  return PERFORMANCE[slug] ?? { level: "lightweight", note: "Static UI with local state; no animation loops." };
}

export const RELATED: Record<string, string[]> = {
  "magnetic-button": ["liquid-button", "magnetic-card", "command-palette"],
  "liquid-button": ["magnetic-button", "magnetic-card"],
  "magnetic-card": ["magnetic-button", "holographic-card", "interactive-3d-card"],
  "slingshot-otp": ["interactive-dropzone", "command-palette"],
  "spatial-command-palette": ["command-palette", "slash-commands", "mention-input"],
  "command-palette": ["spatial-command-palette", "slash-commands"],
  "streaming-chat": ["attachment-prompt", "model-selector", "token-meter", "tool-call-viz", "agent-timeline", "ai-review-edit"],
  "agent-timeline": ["tool-call-viz", "streaming-chat", "audit-log"],
  "tool-call-viz": ["agent-timeline", "streaming-chat"],
  "attachment-prompt": ["streaming-chat", "interactive-dropzone"],
  "ai-review-edit": ["diff-viewer", "version-history", "comment-thread"],
  "diff-viewer": ["ai-review-edit", "version-history"],
  "advanced-table": ["spreadsheet-grid", "query-builder", "audit-log", "env-manager"],
  "spreadsheet-grid": ["advanced-table", "query-builder"],
  "query-builder": ["advanced-table", "spreadsheet-grid"],
  "audit-log": ["log-viewer", "webhook-viewer", "agent-timeline"],
  "version-history": ["diff-viewer", "ai-review-edit", "comment-thread"],
  terminal: ["file-tree", "code-editor", "api-request-builder", "command-palette"],
  "file-tree": ["terminal", "code-editor"],
  "code-editor": ["terminal", "file-tree", "rich-text-editor", "slash-commands"],
  "api-request-builder": ["terminal", "webhook-viewer", "env-manager"],
  "webhook-viewer": ["api-request-builder", "log-viewer", "audit-log"],
  "env-manager": ["api-request-builder", "feature-flags"],
  "cron-builder": ["workflow-builder", "timeline-editor"],
  "kanban": ["node-editor", "workflow-builder", "timeline-editor", "calendar", "approval-workflow"],
  "node-editor": ["kanban", "workflow-builder"],
  "workflow-builder": ["kanban", "node-editor", "approval-workflow", "cron-builder"],
  "timeline-editor": ["kanban", "workflow-builder"],
  "calendar": ["kanban", "cron-builder"],
  "markdown-editor": ["mention-input", "comment-thread", "rich-text-editor", "slash-commands"],
  "mention-input": ["slash-commands", "comment-thread", "markdown-editor"],
  "comment-thread": ["mention-input", "version-history", "ai-review-edit"],
  "rich-text-editor": ["markdown-editor", "slash-commands"],
  "slash-commands": ["mention-input", "command-palette", "rich-text-editor"],
  button: ["magnetic-button", "liquid-button", "ripple-button", "hold-button"],
  input: ["textarea", "tui-form", "invite-flow"],
  textarea: ["input", "rich-text-editor"],
  badge: ["avatar", "kbd"],
  switch: ["checkbox", "feature-flags"],
  checkbox: ["switch", "radio-group"],
  "radio-group": ["checkbox", "switch"],
  slider: ["magnetic-button", "tui-gauge"],
  progress: ["spinner", "skeleton", "tui-progress"],
  spinner: ["progress", "skeleton", "tui-spinner"],
  skeleton: ["spinner", "progress"],
  avatar: ["badge", "team-switcher"],
  kbd: ["tooltip", "command-palette", "tui-help-overlay"],
  separator: ["tabs", "accordion"],
  tabs: ["accordion", "separator"],
  accordion: ["tabs", "comment-thread"],
  toast: ["creative-notifications", "tooltip"],
  tooltip: ["hover-card", "kbd"],
  dialog: ["alert-dialog", "sheet", "modal-stack", "popover"],
  "alert-dialog": ["dialog", "approval-workflow", "hold-button"],
  sheet: ["drawer", "dialog"],
  drawer: ["sheet", "dialog"],
  popover: ["dialog", "tooltip", "dropdown-menu"],
  "dropdown-menu": ["context-menu", "popover", "command-palette"],
  "context-menu": ["dropdown-menu", "popover"],
  "hover-card": ["tooltip", "popover"],
  "modal-stack": ["dialog", "sheet", "approval-workflow"],
  navbar: ["floating-navbar", "sidebar", "mobile-nav", "breadcrumb"],
  "floating-navbar": ["navbar", "mobile-nav"],
  sidebar: ["expandable-sidebar", "navbar", "file-tree", "tui-tree"],
  "expandable-sidebar": ["sidebar", "navbar"],
  "mobile-nav": ["navbar", "floating-navbar"],
  breadcrumb: ["navbar", "pagination", "step-nav"],
  "step-nav": ["breadcrumb", "pagination", "workflow-builder"],
  pagination: ["advanced-table", "breadcrumb"],
  "command-bar": ["command-palette", "spatial-command-palette", "slash-commands"],
  "tui-panel": ["tui-header", "tui-footer", "tui-status-bar", "terminal-workspace"],
  "tui-status-bar": ["tui-panel", "tui-footer"],
  "tui-header": ["tui-panel", "tui-footer"],
  "tui-footer": ["tui-panel", "tui-header", "tui-status-bar"],
  "tui-table": ["advanced-table", "tui-tree", "tui-list"],
  "tui-tree": ["file-tree", "tui-table", "sidebar"],
  "tui-list": ["tui-table", "command-palette"],
  "tui-form": ["input", "tui-select", "invite-flow"],
  "tui-select": ["tui-multi-select", "tui-form", "model-selector"],
  "tui-multi-select": ["tui-select", "query-builder"],
  "tui-progress": ["progress", "tui-gauge", "tui-spinner"],
  "tui-spinner": ["spinner", "tui-progress"],
  "tui-gauge": ["tui-progress", "tui-sparkline", "usage-dashboard"],
  "tui-sparkline": ["tui-gauge", "usage-dashboard"],
  "tui-log-viewer": ["log-viewer", "webhook-viewer", "audit-log"],
  "tui-help-overlay": ["kbd", "command-palette"],
  "tui-diff-viewer": ["diff-viewer", "ai-review-edit"],
  "terminal-workspace": ["terminal", "tui-panel", "file-tree", "command-palette"],
  "noise-background": ["grid-background", "aurora-background"],
  "grid-background": ["dot-grid-background", "noise-background"],
  "dot-grid-background": ["grid-background", "noise-background"],
  "gradient-mesh-background": ["aurora-background", "aurora-beam-background"],
  "aurora-beam-background": ["aurora-background", "beam-background"],
  "ripple-background": ["particle-field", "meteor-background"],
  "meteor-background": ["particle-field", "ripple-background"],
  "beam-background": ["aurora-beam-background", "meteor-background"],
  "glow-cursor": ["blob-cursor", "spotlight-cursor", "cursor-spotlight"],
  "blob-cursor": ["glow-cursor", "ghost-cursor"],
  "trail-cursor": ["ghost-cursor", "particle-field"],
  "ghost-cursor": ["trail-cursor", "blob-cursor"],
  "spotlight-cursor": ["glow-cursor", "cursor-spotlight"],
  typewriter: ["morphing-typography", "scrambled-text"],
  "scrambled-text": ["typewriter", "glitch-text"],
  "blur-text": ["gradient-text", "morphing-typography"],
  "gradient-text": ["blur-text", "glitch-text"],
  "glitch-text": ["scrambled-text", "gradient-text"],
  "ripple-button": ["magnetic-button", "shimmer-button", "glow-button"],
  "shimmer-button": ["ripple-button", "glow-button"],
  "glow-button": ["magnetic-button", "gradient-border-button"],
  "gradient-border-button": ["glow-button", "magnetic-button"],
  "hold-button": ["alert-dialog", "approval-workflow", "magnetic-button"],
  "glare-card": ["magnetic-card", "holographic-card", "spotlight-card"],
  "spotlight-card": ["magnetic-card", "glare-card", "glass-card"],
  "wobble-card": ["magnetic-card", "glare-card"],
  "glass-card": ["spotlight-card", "magnetic-card"],
  "bento-grid": ["masonry-layout", "spotlight-card"],
  "infinite-marquee": ["masonry-layout", "particle-field"],
  "masonry-layout": ["bento-grid", "infinite-marquee"],
  "pricing-table": ["usage-dashboard", "team-switcher", "onboarding-checklist"],
  "team-switcher": ["invite-flow", "pricing-table"],
  "invite-flow": ["team-switcher", "approval-workflow"],
  "approval-workflow": ["kanban", "workflow-builder", "invite-flow", "audit-log"],
  "feature-flags": ["env-manager", "audit-log"],
};

export function relatedFor(slug: string): string[] {
  return RELATED[slug] ?? [];
}

export const A11Y_NOTES: Record<string, string> = {
  "magnetic-button": "Native button; keyboard, focus ring, disabled intact. Motion off under reduced motion.",
  "slingshot-otp": "Game mode is pointer-driven; Standard Mode toggle exposes a labeled input with SR progress.",
  kanban: "Cards focusable; Alt+Arrow moves columns. Drag has a keyboard equivalent.",
  "command-palette": "Combobox/listbox with arrow-key navigation and active-descendant.",
  "spatial-command-palette": "Same combobox contract as base palette plus depth presentation.",
  "streaming-chat": "Log region with polite live updates; input labeled.",
  "token-meter": "Role meter with value now/min/max.",
  terminal: "Log region for output; command input labeled.",
  "file-tree": "Tree role with expand/collapse buttons.",
  "advanced-table": "Semantic table; sortable headers as buttons with sort labels.",
  "spreadsheet-grid": "Every cell input labeled by column letter + row number.",
  "env-manager": "Reveal toggles use aria-pressed; copy announces via button label swap.",
  "feature-flags": "Switches expose aria-checked with accessible names.",
  "invite-flow": "Label-above-input; inline error with role alert; custom validation via noValidate.",
  "timeline-editor": "Clips are buttons with pressed state; selection announced via status.",
  dialog: "Focus trapped and restored; Escape closes; overlay click is configurable.",
  "alert-dialog": "Confirm/cancel with descriptive title; destructive tone announced.",
  sheet: "Focus managed on open; Escape and overlay dismissal supported.",
  popover: "Anchored panel; trigger controls open state; Escape closes.",
  "dropdown-menu": "Menu with item roles; keyboard navigable from trigger.",
  "context-menu": "Right-click surface with a keyboard-operable trigger fallback.",
  "hover-card": "Delayed reveal; trigger remains the semantic control.",
  "modal-stack": "Stacked modals with push/pop; focus follows the top entry.",
  tabs: "Tablist semantics with arrow-key movement between tabs.",
  accordion: "Disclosure buttons expose expanded state per section.",
  toast: "Live-region announcements for transient messages.",
  switch: "Native checkbox semantics with label and pressed state.",
  "radio-group": "Single-select group with arrow-key navigation.",
  navbar: "Banner landmark with navigable links.",
  breadcrumb: "Ordered trail; current page marked for screen readers.",
  pagination: "Numbered page buttons with current-page state.",
  "mobile-nav": "Labeled bottom navigation items.",
  "tui-table": "Monospace grid with row selection state.",
  "tui-form": "Labeled terminal fields with submit action.",
  "terminal-workspace": "Tabbed terminal with labeled panes and command input.",
  "hold-button": "Press-and-hold has a keyboard-operable equivalent; progress announced.",
  "glow-cursor": "Pointer-only effect; null under reduced motion. Never the sole interaction.",
};

export function a11yFor(slug: string): string {
  return (
    A11Y_NOTES[slug] ??
    "Semantic HTML with labeled controls, visible focus, and reduced-motion-safe behavior."
  );
}
